name: seal-build

on:
  workflow_dispatch: {}

jobs:
  pack:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.12.0
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Build
        run: npm run build
      - name: Pack
        run: npm pack
      - uses: actions/upload-artifact@v4
        with:
          name: npm-tarball
          path: sift-*.tgz
          if-no-files-found: error
